### ISSUE TITLE
Reactivate tests: disabled tests collection

### ISSUE THREAD

**Issue by HeikoKlare** [eclipse-platform/eclipse.platform#525]
### Current Situation
Several tests have been deactivated over the years for different reasons, such as temporary incompatibilities with a specific platform/OS, bugs in the code, indeterministic behavior of the test etc.

These disablements are done by adding some prefix to `test...` methods in JUnit 3, by removing or commenting out `@Test` in JUnit 4 and 5, or by using `@Ignore` or `@Disabled`. In addition, several tests are only deactivated for specific platforms using early returns or assume statements within the test methods.

### Goal
Since in most cases there is no additional, unique documentation or tagging of these disablements, they are not easy to find. This issue is supposed to be an umbrella to document disabled tests (existing ones and potentially further ones).

The purpose of this issue is to collect the disabled tests to have a central overview and provide the chance to reactivate and, if necessary, fix them. It also serves as a "good first issue" (see https://github.com/eclipse-platform/eclipse.platform.text/pull/212#issuecomment-1594576748) for interested new contributors, which can take any of the collected tests and try to fix them to learn about the Eclipse platform code while, at the same time, already having the chance to make valuable contributions to the project.

### Process
I see the following ideas as good starting points for identifying disabled tests:
- First concentrate on a single project, such as `org.eclipse.core.tests.resources`
- Use different techniques to find disabled tests:
    1. Completely disabled tests:
        - Search for missing or commented out `@Test` annotation (JUnit 4 and 5)
        - Search for tests not starting with `test` (JUnit 3), in particular those starting with `_test`
    2. Tests disabled for specific platforms:
        - Search for accesses to OS constants in `Platform`, such as `OS_WIN32` and validate if they are used to disable tests for specific platforms
        - Search for accesses to methods `isLinux()` etc. in `ResourceTest` subclasses and validate if they are used to disable tests for specific platforms
        - Search for `assumeFalse` or `assumeTrue` statements that make tests only run on specific platforms

#### Examples
- The tests modified in https://github.com/eclipse-platform/eclipse.platform.text/pull/212
- Tests in `org.eclipse.core.tests.resources.regression.Bug_032076`
- The `skipTest` helper in `org.eclipse.core.tests.resources.usecase.SnapshotTest`

### Disabled in Maven
Some tests are disabled in Maven builds, such that integration builds do not reveal whether they fail or not.
- [ ] The bundle [`org.eclipse.core.tests.net`](https://github.com/eclipse-platform/eclipse.platform/blob/cebe637f94a94480c00b24f29d460ec163ba973c/team/tests/org.eclipse.core.tests.net/pom.xml#L28) is completely disabled. Tests run fine withing Eclipse on Windows, but Tycho execution fails, probably because of missing platform-dependent fragments (maybe have a look at how SWT deals with that).
- [ ] `org.eclipse.team.tests.core.AllTeamUITests` and `org.eclipse.team.tests.ui.synchronize.AllTeamSynchronizeTests` are not executed as the test suite [only executes `org.eclipse.team.tests.core.AllTeamTests`](https://github.com/eclipse-platform/eclipse.platform/blob/cebe637f94a94480c00b24f29d460ec163ba973c/team/tests/org.eclipse.team.tests.core/pom.xml#L26). Tests run fine within Eclipse on WIndows, but Tycho fails to execute some of the `ScopeTests` and the `AllTeamSynchronizeTest`.

**Comment by Wittmaxi** [comment]
Performing a naive search for `_test`, `@Ignore`, `@Disabled`, I found quite some artifacts which are worth adding to this issue

### org.eclipse.core.tests.resources 
- [ ] [SymLinkTest#testSymlinkExtendedChars()](https://github.com/eclipse-platform/eclipse.platform/blob/bfc1919683f5753055e41319695478ded0f688dc/resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/filesystem/SymlinkTest.java#L377), [(issue)](https://bugs.eclipse.org/bugs/show_bug.cgi?id=172346) - Enabling this test works in my native environment, I will test it in an headless-environment next. Notably, the very recently introduced [assumeCanCreateSymLinks()](https://github.com/eclipse-platform/eclipse.platform/blob/bfc1919683f5753055e41319695478ded0f688dc/resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/filesystem/SymlinkTest.java#L379)([commit](https://github.com/eclipse-platform/eclipse.platform/commit/cdf452ffd496a1d096de046c59a93f3363a34a36)) requires administrator rights on windows to enable this test.
### org.eclipse.core.tests.runtime
- [ ] [ServiceSupplierTestCase#testUselessUpdates()](https://github.com/eclipse-platform/eclipse.platform/blob/bfc1919683f5753055e41319695478ded0f688dc/runtime/tests/org.eclipse.e4.core.tests/src/org/eclipse/e4/core/internal/tests/di/extensions/ServiceSupplierTestCase.java#L295), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=572546) - this is a relatively new issue
- [ ] [EclipsePreferencesTest#testRemoveDeletesFile()](https://github.com/eclipse-platform/eclipse.platform/blob/bfc1919683f5753055e41319695478ded0f688dc/runtime/tests/org.eclipse.core.tests.runtime/src/org/eclipse/core/tests/internal/preferences/EclipsePreferencesTest.java#L661), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=367366) - Status CLOSED WONTFIX
- [ ] [BeginEndRuleTest#testEndNullRule()](https://github.com/eclipse-platform/eclipse.platform/blob/bfc1919683f5753055e41319695478ded0f688dc/runtime/tests/org.eclipse.core.tests.runtime/src/org/eclipse/core/tests/runtime/jobs/BeginEndRuleTest.java#L320), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=43460) - RESOLVED WONTFIX
- [ ] [DeadlockDetectionTest#testRuleHierarchyLockInteraction()](https://github.com/eclipse-platform/eclipse.platform/blob/bfc1919683f5753055e41319695478ded0f688dc/runtime/tests/org.eclipse.core.tests.runtime/src/org/eclipse/core/tests/runtime/jobs/DeadlockDetectionTest.java#L812), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=46894)
- [ ] [DeadlockDetectionTest#testComplexRuleLockInteraction()](https://github.com/eclipse-platform/eclipse.platform/blob/bfc1919683f5753055e41319695478ded0f688dc/runtime/tests/org.eclipse.core.tests.runtime/src/org/eclipse/core/tests/runtime/jobs/DeadlockDetectionTest.java#L1023), no issue
- [ ] [DeadlockDetectionTest#testJobRuleCancellation](https://github.com/eclipse-platform/eclipse.platform/blob/bfc1919683f5753055e41319695478ded0f688dc/runtime/tests/org.eclipse.core.tests.runtime/src/org/eclipse/core/tests/runtime/jobs/DeadlockDetectionTest.java#L1103), no issue
- [ ] [DeadlockDetectionTest#testLockMultipleAcquireThenSuspend](https://github.com/eclipse-platform/eclipse.platform/blob/bfc1919683f5753055e41319695478ded0f688dc/runtime/tests/org.eclipse.core.tests.runtime/src/org/eclipse/core/tests/runtime/jobs/DeadlockDetectionTest.java#L1161), no issue
- [ ] [JobTest#testDone()](https://github.com/eclipse-platform/eclipse.platform/blob/bfc1919683f5753055e41319695478ded0f688dc/runtime/tests/org.eclipse.core.tests.runtime/src/org/eclipse/core/tests/runtime/jobs/JobTest.java#L47), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=43591) - RESOLVED WONTFIX - For this test, the documented behaviour of Job.done() needs to be understood and checked against the test. If the test does not check for documented behaviour, the test itself needs to be rewritten.

**Comment by Michael5601** [comment]
Addition to https://github.com/eclipse-platform/eclipse.platform/issues/525#issuecomment-1613014550.
Checked tests have pending or accepted PR:

### org.eclipse.core.tests.resources
* [ ]  [RefreshJobTest#XtestSmallRecursionRefresh()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/resources/refresh/RefreshJobTest.java#L147) - test is disabled because it needs 400 seconds on fast SSD on Linux
* [ ]  [RefreshJobTest#XtestBigRecursionDeepRefresh()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/resources/refresh/RefreshJobTest.java#L170) - test is disabled because it needs 250 seconds on fast SSD on Linux
* [ ]  [RefreshJobTest#XtestUnrelatedRule()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/resources/refresh/RefreshJobTest.java#L251) - test is disabled because it is unstable
* [ ]  [Bug_079398#testBug79398()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/resources/regression/Bug_079398.java#L29), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=079398) - test is not hooked up because bug is not fixed yet
* [ ]  [IFileTest#testBug25658()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/resources/regression/IFileTest.java#L34), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=25658) - bug seems to be fixed but test is still disabled. Can only be tested on Linux.
* [ ]  [VirtualFolderTest#testIsLocal()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/resources/VirtualFolderTest.java#L403) - test is commented out
* [ ]  [VirtualFolderTest#testIsSynchronizedforVirtualFolder()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/resources/VirtualFolderTest.java#L414) - test is commented out
* [ ]  [LinkedResourceWithPathVariableTest#testGetPathVariable()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/resources/LinkedResourceWithPathVariableTest.java#L1268) - test is commented out
* [ ]  [ISynchronizerTest#testSnap()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/resources/ISynchronizerTest.java#L600) - test is commented out
* [ ]  [IWorkspaceTest#testValidateLinkLocation()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/resources/IWorkspaceTest.java#L795) - test is commented out
* [ ]  [RefreshLocalTest#testDiscoverLinkedResource()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/internal/localstore/RefreshLocalTest.java#L59) - test is commented out
* [ ]  [Bug552185PerformanceTest#testBug552185Performance()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/internal/resources/Bug552185PerformanceTest.java#L29), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=552185) - not included in actual tests, since performance is only printed and not asserted.
* [x] ~~[Bug_029851#test()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/resources/tests/org.eclipse.core.tests.resources/src/org/eclipse/core/tests/resources/regression/Bug_029851.java#L53), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=029851)~~ disabled but works fine, fixed via #603

### org.eclipse.core.tests.runtime
* [ ]  [PreferencesServiceTest#testApplyWithTransfers()](https://github.com/eclipse-platform/eclipse.platform/blob/bfc1919683f5753055e41319695478ded0f688dc/runtime/tests/org.eclipse.core.tests.runtime/src/org/eclipse/core/tests/internal/preferences/PreferencesServiceTest.java#L1225) - not implemented yet
* [ ]  [YieldTest#testILockTransfer()](https://github.com/eclipse-platform/eclipse.platform/blob/bfc1919683f5753055e41319695478ded0f688dc/runtime/tests/org.eclipse.core.tests.runtime/src/org/eclipse/core/tests/runtime/jobs/YieldTest.java#L238) - test is commented out

### org.eclipse.ant.tests.ui
* [ ]  [OccurrencesFinderTests#testPropertyRefFromTaskText2()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/ant/org.eclipse.ant.tests.ui/Ant%20Editor%20Tests/org/eclipse/ant/tests/ui/editor/OccurrencesFinderTests.java#L299), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=94123)  - test is commented out
* [ ]  [NonInitialTypingTest](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/ant/org.eclipse.ant.tests.ui/Ant%20Editor%20Tests/org/eclipse/ant/tests/ui/editor/performance/NonInitialTypingTest.java) - class is commented out
* [ ]  [SteppingTests#testStepBackFromAnt()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/ant/org.eclipse.ant.tests.ui/Ant%20Debug%20Tests/org/eclipse/ant/tests/ui/debug/SteppingTests.java#L224) - test is commented out
* [ ]  [SteppingTests#testStepBackFromAntSepVM()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/ant/org.eclipse.ant.tests.ui/Ant%20Debug%20Tests/org/eclipse/ant/tests/ui/debug/SteppingTests.java#L228) - test is commented out
* [ ]  [SteppingTests#testStepIntoAnt()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/ant/org.eclipse.ant.tests.ui/Ant%20Debug%20Tests/org/eclipse/ant/tests/ui/debug/SteppingTests.java#L233) - test is commented out
* [ ]  [SteppingTests#testStepIntoAntSepVM()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/ant/org.eclipse.ant.tests.ui/Ant%20Debug%20Tests/org/eclipse/ant/tests/ui/debug/SteppingTests.java#L237) - test is commented out
* [ ]  [SteppingTests#testStepOverAnt()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/ant/org.eclipse.ant.tests.ui/Ant%20Debug%20Tests/org/eclipse/ant/tests/ui/debug/SteppingTests.java#L241) - test is commented out
* [ ]  [SteppingTests#testStepOverAntSepVM()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/ant/org.eclipse.ant.tests.ui/Ant%20Debug%20Tests/org/eclipse/ant/tests/ui/debug/SteppingTests.java#L245) - test is commented out
* [ ]  [BuildTests#testBuildFailedMessageDebug()](https://github.com/eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/ant/org.eclipse.ant.tests.ui/Ant%20Tests/org/eclipse/ant/tests/ui/BuildTests.java#L174), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=42333) - test is commented out
* [ ]  [BuildTests#testLinksDebug()](https://github.com/eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/ant/org.eclipse.ant.tests.ui/Ant%20Tests/org/eclipse/ant/tests/ui/BuildTests.java#L188), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=42333) - test is commented out
* [ ]  [BuildTests#testColorDebug()](https://github.com/eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/ant/org.eclipse.ant.tests.ui/Ant%20Tests/org/eclipse/ant/tests/ui/BuildTests.java#L214), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=42333) - test is commented out

### org.eclipse.core.expressions.tests
* [x] ~~[CountExpressionTest#testLessThanOrEqualToExpression()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/runtime/tests/org.eclipse.core.expressions.tests/src/org/eclipse/core/internal/expressions/tests/CountExpressionTest.java#L68)~~ - fixed via #625
* [x] ~~[CountExpressionTest#testGreaterThanOrEqualToExpression()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/runtime/tests/org.eclipse.core.expressions.tests/src/org/eclipse/core/internal/expressions/tests/CountExpressionTest.java#L83)~~ - fixed via #625

### org.eclipse.e4.core.tests
* [ ]  [ServiceSupplierTestCase#testUselessUpdates()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/runtime/tests/org.eclipse.e4.core.tests/src/org/eclipse/e4/core/internal/tests/di/extensions/ServiceSupplierTestCase.java#L295), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=572546) - NEW BUG

### org.eclipse.debug.tests
* [x] ~~[SerialExecutorTest#testHeavyScheduling()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/debug/org.eclipse.debug.tests/src/org/eclipse/debug/tests/breakpoint/SerialExecutorTest.java#L122), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=574883)~~ - test is disabled but working because bug is already fixed, enabled via #617 
* [x] ~~[ConsoleDocumentAdapterTests#_testInvalidInvocations()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/debug/org.eclipse.debug.tests/src/org/eclipse/debug/tests/console/ConsoleDocumentAdapterTests.java#L942)~~ - test is disabled but working, enabled via #617
* [ ]  [RuntimeProcessTests#testOutputAfterDestroy()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/debug/org.eclipse.debug.tests/src/org/eclipse/debug/tests/console/RuntimeProcessTests.java#L220), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=577189) - NEW BUG
* [x]  ~~[CheckTests#testCheckReceiver()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/debug/org.eclipse.debug.tests/src/org/eclipse/debug/tests/viewer/model/CheckTests.java#L78)~~ - test is commented out, reenabled with #681.
* [ ]  [ContentTests#_x_testChildrenUpdatesCompletedOutOfSequence()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/debug/org.eclipse.debug.tests/src/org/eclipse/debug/tests/viewer/model/ContentTests.java#L257), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=210027) - test works locally if reactivated but fails in [CI builds](https://github.com/eclipse-platform/eclipse.platform/actions/runs/5797054163/job/15711848346?pr=617#step:7:18372), so it should remain disabled
* [ ]  [DeltaTests#_x_testAddUnexpandedElement()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/debug/org.eclipse.debug.tests/src/org/eclipse/debug/tests/viewer/model/DeltaTests.java#L342), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=311442) - RESOLVED WORKSFORME is bug status, but the test fails on windows
* [ ]  [DeltaTests#_x_testRefreshUnexpandedElementsChildren()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/debug/org.eclipse.debug.tests/src/org/eclipse/debug/tests/viewer/model/DeltaTests.java#L390) - test fails
* [ ]  [JFaceViewerDeltaTests#testBug292322()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/debug/org.eclipse.debug.tests/src/org/eclipse/debug/tests/viewer/model/JFaceViewerDeltaTests.java#L40), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=292322) - comment states that test should be deleted after bug is fixed. But after reactivation the test does not terminate. It is not executed during CI builds (they run the VirtualViewerContentTests rather than the JFaceViewerDeltaTests), so that CI builds do not reveal that failure. Test should remain disabled.
* [ ]  [VirtualViewerLazyModeTests#test()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/debug/org.eclipse.debug.tests/src/org/eclipse/debug/tests/viewer/model/VirtualViewerLazyModeTests.java#L45) - test is not yet implemented
* [x] ~~[FilterTest#testVerify()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/team/tests/org.eclipse.compare.tests/src/org/eclipse/compare/tests/FilterTest.java#L63)~~ - test is commented out, enabled via #679 

### org.eclipse.core.tests.net.NetTest
* [ ]  [NetTest#_testSimpleHost()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/team/tests/org.eclipse.core.tests.net/src/org/eclipse/core/tests/net/NetTest.java#L282), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=403311) - enabled in #618 but failed in CI builds, thus disabled again via #633

### org.eclipse.team.tests.core
* [x] ~~[ScopeTests#testScopeContraction()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/team/tests/org.eclipse.team.tests.core/src/org/eclipse/team/tests/core/mapping/ScopeTests.java#L110)~~ - disabled but working, enabled via #619
* [x]  [ResourceContentTests#testFileChange()](https://github.com/Eclipse-platform/eclipse.platform/blob/24c00e9fc70602c8e71ea80145227f8361bcbd3c/team/tests/org.eclipse.team.tests.core/src/org/eclipse/team/tests/ui/synchronize/ResourceContentTests.java#L193) - test is commented out

### org.eclipse.tips.tests
* [x]  [TipImageBas64Test#testSetExtension()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.tips.tests/src/org/eclipse/tips/core/TipImageBas64Test.java#L43) - test is commented out
* [x]  [TipImageBas64Test#testSetExtension2()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.tips.tests/src/org/eclipse/tips/core/TipImageBas64Test.java#L48) - test is commented out
* [x]  [TipImageURLTest#testSetExtension()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.tips.tests/src/org/eclipse/tips/core/TipImageURLTest.java#L98) - test is commented out
* [x]  [TipImageURLTest#testSetExtension2()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.tips.tests/src/org/eclipse/tips/core/TipImageURLTest.java#L103) - test is commented out
* [x]  ~~[Good#test()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.tips.tests/src/org/eclipse/tips/tests/Good.java#L23)~~ - useless test, removed via #620

### org.eclipse.ua.tests
* [ ]  [ContextTest#testCopyContextWithAttribute()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/other/ContextTest.java#L423) - test is commented out, enabled via https://github.com/eclipse-platform/eclipse.platform/pull/2599
* [x] ~~[IndexEntryTest#testUserEntryChildEnablement()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/other/IndexEntryTest.java#L292), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=210024)~~ - test is commented out, enbaled via #621
* [ ]  [TopicTest#testCopyTopicWithChildRemoveChild()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/other/TopicTest.java#L133), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=210024) - test is commented out
* [ ]  [TopicTest#testCopyTopicWithChildCheckParents()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/other/TopicTest.java#L152), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=210024) - test is commented out
* [ ]  [LocaleTest#testSearchQualifiedNames_de()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/search/LocaleTest.java#L121), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=219928) - test is commented out
* [ ]  [TocModelSerializerTest#testRunSerializer()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/util/TocModelSerializerTest.java#L59) - test is commented out
* [ ]  [AdvancedSearchServiceTest#testRemoteSearchJSONSchema()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/webapp/service/AdvancedSearchServiceTest.java#L79) - test is not yet implemented
* [ ]  [ContextServiceTest#testContextServiceJSONSchema()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/webapp/service/ContextServiceTest.java#L61) - test is not yet implemented
* [ ]  [ExtensionServiceTest#testExtensionFragmentServiceJSONSchema()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/webapp/service/ExtensionServiceTest.java#L168) - test is not yet implemented
* [ ]  [IndexFragmentServiceTest#testIndexFragmentServiceJSONSchema()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/webapp/service/IndexFragmentServiceTest.java#L84) - test is not yet implemented
* [ ]  [SchemaValidator#testJSONSchema()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/webapp/service/SchemaValidator.java#L54) - test is not yet implemented
* [ ]  [TocFragmentServiceTest#testTocFragmentServiceJSONSchema()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/webapp/service/TocFragmentServiceTest.java#L222) - test is not yet implemented
* [ ]  [TocServiceTest#testTocServiceJSONSchema()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/webapp/service/TocServiceTest.java#L60) - test is commented out
* [x] ~~[TocServiceTest#testTocServiceXMLSchema()](https://github.com/eclipse-platform/eclipse.platform/blob/18d0171854eec533f733f60d0c278acdf0c9f8ae/ua/org.eclipse.ua.tests/help/org/eclipse/ua/tests/help/webapp/service/TocServiceTest.java#L47), [issue](https://bugs.eclipse.org/bugs/show_bug.cgi?id=339274)~~ - test is commented out but working, enabled via #621
